#include "token_kind.h"

#define TOKEN_CASE(kind)                                                                                               \
  case kind:                                                                                                           \
    return #kind;

char* token_kind_str(TokenKind kind) {
  switch (kind) {
    TOKEN_CASE(TOK_DESTRUCTOR);
    TOKEN_CASE(TOK_EMTPY);
    TOKEN_CASE(TOK_RANGEINCL);
    TOKEN_CASE(TOK_UNIT);
    TOKEN_CASE(TOK_STRING);
    TOKEN_CASE(TOK_FLOAT);
    TOKEN_CASE(TOK_INTEGER);
    TOKEN_CASE(TOK_RANGE);
    TOKEN_CASE(TOK_PATH);
    TOKEN_CASE(TOK_COMMENT);
    TOKEN_CASE(TOK_DECIMAL);
    TOKEN_CASE(TOK_COMMA);
    TOKEN_CASE(TOK_INVALID);
    TOKEN_CASE(TOK_QMARK);
    TOKEN_CASE(TOK_DQUOTE);
    TOKEN_CASE(TOK_SQUOTE);
    TOKEN_CASE(TOK_EXCLAM);
    TOKEN_CASE(TOK_COLON);
    TOKEN_CASE(TOK_XOR);
    TOKEN_CASE(TOK_PERCENT);
    TOKEN_CASE(TOK_BINV);
    TOKEN_CASE(TOK_MINUS);
    TOKEN_CASE(TOK_PLUS);
    TOKEN_CASE(TOK_DOLLAR);
    TOKEN_CASE(TOK_TICK);
    TOKEN_CASE(TOK_STAR);
    TOKEN_CASE(TOK_FSLASH);
    TOKEN_CASE(TOK_BSLASH);
    TOKEN_CASE(TOK_LBRACE);
    TOKEN_CASE(TOK_RBRACE);
    TOKEN_CASE(TOK_AT);
    TOKEN_CASE(TOK_EQ);
    TOKEN_CASE(TOK_LPAREN);
    TOKEN_CASE(TOK_RPAREN);
    TOKEN_CASE(TOK_POUND);
    TOKEN_CASE(TOK_AMPER);
    TOKEN_CASE(TOK_LBRACK);
    TOKEN_CASE(TOK_RBRACK);
    TOKEN_CASE(TOK_PIPE);
    TOKEN_CASE(TOK_LOR);
    TOKEN_CASE(TOK_LAND);
    TOKEN_CASE(TOK_SHL);
    TOKEN_CASE(TOK_SHR);
    TOKEN_CASE(TOK_GT);
    TOKEN_CASE(TOK_LT);
    TOKEN_CASE(TOK_GTE);
    TOKEN_CASE(TOK_LTE);
    TOKEN_CASE(TOK_EQEQ);
    TOKEN_CASE(TOK_NOTEQ);
    TOKEN_CASE(TOK_PLUSEQ);
    TOKEN_CASE(TOK_MINEQ);
    TOKEN_CASE(TOK_TIMESEQ);
    TOKEN_CASE(TOK_DIVEQ);
    TOKEN_CASE(TOK_BINVEQ);
    TOKEN_CASE(TOK_ANDEQ);
    TOKEN_CASE(TOK_OREQ);
    TOKEN_CASE(TOK_XOREQ);
    TOKEN_CASE(TOK_MODEQ);
    TOKEN_CASE(TOK_SHLEQ);
    TOKEN_CASE(TOK_SHREQ);
    TOKEN_CASE(TOK_KW_AS);
    TOKEN_CASE(TOK_KW_ASYNC);
    TOKEN_CASE(TOK_KW_AWAIT);
    TOKEN_CASE(TOK_KW_BREAK);
    TOKEN_CASE(TOK_KW_CONST);
    TOKEN_CASE(TOK_KW_CONTINUE);
    TOKEN_CASE(TOK_KW_ELSE);
    TOKEN_CASE(TOK_KW_ENUM);
    TOKEN_CASE(TOK_KW_FALSE);
    TOKEN_CASE(TOK_KW_FN);
    TOKEN_CASE(TOK_KW_FOR);
    TOKEN_CASE(TOK_KW_IF);
    TOKEN_CASE(TOK_KW_IMPL);
    TOKEN_CASE(TOK_KW_IN);
    TOKEN_CASE(TOK_KW_VAR);
    TOKEN_CASE(TOK_KW_LET);
    TOKEN_CASE(TOK_KW_MATCH);
    TOKEN_CASE(TOK_KW_MODULE);
    // TOKEN_CASE(TOK_KW_MUT);
    TOKEN_CASE(TOK_KW_PUB);
    TOKEN_CASE(TOK_KW_REF);
    TOKEN_CASE(TOK_KW_RETURN);
    TOKEN_CASE(TOK_KW_SELF);
    TOKEN_CASE(TOK_KW_SELFTYPE);
    TOKEN_CASE(TOK_KW_STATIC);
    TOKEN_CASE(TOK_KW_STRUCT);
    TOKEN_CASE(TOK_KW_SUPER);
    TOKEN_CASE(TOK_KW_TRAIT);
    TOKEN_CASE(TOK_KW_TRUE);
    TOKEN_CASE(TOK_KW_TYPE);
    TOKEN_CASE(TOK_KW_USE);
    TOKEN_CASE(TOK_KW_WHILE);
    TOKEN_CASE(TOK_KW_YIELD);
    TOKEN_CASE(TOK_SEMICOLON);
    TOKEN_CASE(TOK_IDENT);
    TOKEN_CASE(TOK_EOF);
    TOKEN_CASE(TOK_ARROW);
  }

  return "TOK_INVALID";
}

// bool is_valid_op(token_kind_t kind) {
//     usize table_len = array_len(valid_ops);
//     for (usize idx = 0; idx < table_len; idx++) {
//         if (kind == valid_ops[idx]) {
//             return true;
//         }
//     }
//
//     return false;
// }
